avicii: Use NxpNfcNci from OB2 for now
* Why OnePlus?

03-02 14:37:35.345  4528  4528 E AndroidRuntime: FATAL EXCEPTION: main
03-02 14:37:35.345  4528  4528 E AndroidRuntime: Process: com.android.nfc, PID: 4528
03-02 14:37:35.345  4528  4528 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/OPDiagnoseManager;
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at com.oneplus.nfc.OPNfcDiagnose.<init>(OPNfcDiagnose.java:23)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at com.oneplus.nfc.OPNfcDiagnose.getInstance(OPNfcDiagnose.java:47)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at com.android.nfc.NfcService.<init>(NfcService.java:675)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at com.android.nfc.NfcApplication.onCreate(NfcApplication.java:66)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6715)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.app.ActivityThread.access(ActivityThread.java:237)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.app.ActivityThread.handleMessage(ActivityThread.java:1913)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.os.Looper.loop(Looper.java:223)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7660)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:592)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-02 14:37:35.345  4528  4528 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.os.OPDiagnoseManager
03-02 14:37:35.345  4528  4528 E AndroidRuntime: ... 14 more